### ISSUE TITLE
Nice examples

### ISSUE THREAD

**Issue by DouglasAllen** [phn/jdcal#1]
But you left out one import't thing. That's right mate. 
What the bloody l do we import for sure? 
import jdcal 
gives me no worries but then something like 
gcal2jd(2000,1,1)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
NameError: name 'gcal2jd' is not defined

So nice to 'ave things so well documented ah gov?
So I did find that 
 jdcal.gcal2jd(2000,1,1)
(2400000.5, 51544.0)
does it's best.

I'm still new to Python and didn't quite know how to import it.
Could you update your webpage about it?
I discovered this in my recent learning:
from jdcal import *
seems to do the trick.
Just for the sake of newbs?

**Comment by phn** [comment]
Hello,

Sorry for the delay in getting to this. 

Thanks for pointing this out. I have updated the code with contribution from @zed that adds more instructions to the readme file.

Regards,
Prasanth
