### ISSUE TITLE
Return minus number when JD less than -65965

### ISSUE THREAD

**Issue by tzengyuxio** [phn/jdcal#8]
jd2gcal() will return invalid date in minus number when JD less than -65965

```
>>> jd2gcal(0, -68964)
(-4901, 2, 1, 0.5)
>>> jd2gcal(0, -68965)
(-4901, 2, 0, 0.5)
>>> jd2gcal(0, -68966)
(-4901, 2, -1, 0.5)
```

more example:
```
>>> jd2gcal(0, -100010)
(-4986, 2, 1, 0.5)
>>> jd2gcal(0, -100011)
(-4986, 2, 0, 0.5)
>>> jd2gcal(0, -100012)
(-4986, 2, -1, 0.5)
>>> jd2gcal(0, -100041)
(-4986, 2, -30, 0.5)
>>> jd2gcal(0, -100042)
(-4986, 1, -1, 0.5)
```

**Comment by phn** [comment]
Hello,

As far as I can tell jdcal's algorithms (modified from TPM) is not designed for negative JDs.

If you are looking for more accurate work, do have a look at astropy (https://github.com/astropy/astropy) and ERFA (https://github.com/liberfa/erfa). Not sure if they work with negative JDs but they are used by professional astronomers.

Regards,
Prasanth
